spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:2600/midware_3rd_party_pos?autoReconnect=true
    username: root
    password: P@ssw0rd.15!
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect
  security:
    oauth2:
      resource:
        filter-order: 3
oauth2:
  tokenUrl: http://localhost:8080/oauth/token
  checkTokenUrl: http://localhost:8080/oauth/check_token
  authorizeTokenUrl: http://localhost:8080/oauth/authorize
  clientId: tester
  clientSecret: tester
  tokenExpired: 60
  refreshToken: 345
mqtt:
  automaticReconnect: true
  cleanSession: false
  connectionTimeout: 10
  clientId: ${COMPUTERNAME}-MQTT
  hostname: localhost
  port: 32771
server:
  port: 8081




